# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and push images.

on:
  #push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo "Hello world the first Github actions pipelines"
    # Build all images
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    # Tag images 
    - run: docker tag reverseproxy jedielade/reverseproxy:v1
    - run: docker tag udagram-api-feed jedielade/udagram-api-feed:v1
    - run: docker tag udagram-api-user jedielade/udagram-api-user:v1
    - run: docker tag udagram-frontend:local jedielade/udagram-frontend:v1
    # En supposant que DOCKER_PASSWORD et DOCKER_USERNAME sont définis dans les paramètres du dépôt Travis
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker push jedielade/udagram-api-feed:v1
    - run: docker push jedielade/udagram-api-user:v1
    - run: docker push jedielade/udagram-frontend:v1
    - run: docker push jedielade/reverseproxy:v1
